### ISSUE TITLE
Migrate install

### ISSUE THREAD

**Issue by carneto** [kanazaca/easypay#1]
Hello,

When i run migrate to create easypay_notifications table,
shows me a error:

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Fatal error: Class 'CreateEasypayNotifications' not found

**Comment by malikahsanraza5** [comment]
Please run this command in cmd where you installed laravel 
composer dump-autoload

**Comment by faizansattar** [comment]
Hello,
I try **composer dump-autoload** command in cmd but still this error was coming in my screen.

PHP Fatal error:  Class 'CreateEasypayNotifications' not found in E:\xampp\htdocs\seedout\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php on line 335

```
[37;41m                                                           [39;49m
[37;41m  [Symfony\Component\Debug\Exception\FatalErrorException]  [39;49m
[37;41m  Class 'CreateEasypayNotifications' not found             [39;49m
[37;41m
```

**Comment by michelmelo** [comment]
I'm making the same mistake. @kanazaca 
tem uma ideia do que pode ser?

**Comment by kanazaca** [comment]
The problem was in the name of the file ... It should have a '_table' at the end 

Otherwise laravel couldn't resolve the class.

**Comment by kanazaca** [comment]
You guys should receive the fix after `composer update`. If not, run `composer clearcache`
